### ISSUE TITLE
How do I download this?  Where do I even begin?

### ISSUE THREAD

**Issue by gaveitatry02** [freaktechnik/twitch-chatlog#105]
God damn it.  I hate it when people like you just assume that everyone has the same amount of knowledge as you do.

Most GitHubs that I go to have links for either direct downloads, download pages, websites that host the downloads, or an official website that has a download link.  Your GitHub is the first that doesn't have that.  It only has a 'Clone or download' button that I never used before.  But from what I've seen online, that is supposed to download an entire repository.  Whatever that is.  Seems like more than what I want.  But okay.  Maybe it is what I need.

So I downloaded the repository, and now I don't even know what to do.  I went into /bin and double clicked twitch-chatlog and that didn't do anything.  Double clicking other files also does nothing.

So I looked at the "ReadMe.md" instructions on your GitHub page.  It said for installation to type "npm install -g twitch-chatlog".  Okay, you ftard.  Try to create a user friendly instruction guide for someone who has no idea where to type that sht at.  I opened up the Command Prompt and typed that in.  It said that 'npm' is not recognized as an internal or external command, operable program or batch file.

How about you give clear, detailed instructions on what to do:
1.) Download this (link provided)
2.) Also download this (link provided)
3.) Open up this.
4.) Type this.
5.) Then do this.

etc.

F piece of sht.  There are a lot of regular computer users that don't even know where to begin, and if you only took 5 mintues to explain detailed instructions and steps, they wouldn't be as completely lost as I am.

**Comment by gaveitatry02** [comment]
So I went to a similar GitHub project (https://github.com/OgulcanCelik/twitch-clip-chat) and his instructions were sht too, but at least he gave me a hint.  He said that you needed Python.  I installed it.  It was less than 100 MB.  But then I got stuck again.  I copied and pasted the "npm install -g twitch-chatlog" command into the Python exe window and it said "invalid syntax".  So I decided to give up on this freaktechnik/twitch-chatlog bullsht and try OgulcanCelik's Twitch Clip Chat! because at least it was giving me instruction clues.  It's instructions were: "git clone https://github.com/OgulcanCelik/twitch-clip-chat.git" and "pip install requests".  I had no idea where to type that or what that does.  I don't even know what requests are.  But I started by clicking the 'Clone or Download' Github button link and downloading the Twitch Clip Chat! repository.  Then I copied pasted "git clone https://github.com/OgulcanCelik/twitch-clip-chat.git" into the Python window.  Again, I got "invalid syntax"  Fck these pc of shit Github devlopers who don't make user friendly guides and instruction for first-time-doing-this users.

**Comment by freaktechnik** [comment]
I will ask youto cool the swearing. This is a tool that requires nodejs and is primarily intended for an audience that is familiar with using nodejs & npm packages. So yes, there are no instructions so everyone, no matter what their knowledge level can install it. I'll hapily help if someone asks nicely, but I'm sad to say this is kind of beyond asking nicely for me.

I hope you can understand that not every repository on GitHub is intended to be as easy to install as a Game or a Browser.
