### ISSUE TITLE
connect ETIMEDOUT 31.13.85.1:443

### ISSUE THREAD

**Issue by LydiaHappy** [freaktechnik/twitch-chatlog#109]
I use npm i install twitch-chatlog in my windowspower shell but it can't link to some address.
I tried proxy but it still didn't work.

Here is the error.

> PS D:\lydia\life\candycrash> twitch-chatlog 79240813
> { FetchError: request to https://api.twitch.tv/kraken/videos/79240813 failed, reason: connect ETIMEDOUT 31.13.85.1:443
>     at ClientRequest.<anonymous> (C:\Users\TF\AppData\Roaming\npm\node_modules\twitch-chatlog\node_modules\node-fetch\lib\index.js:1455:11)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at TLSSocket.socketErrorListener (_http_client.js:387:9)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
>   message: 'request to https://api.twitch.tv/kraken/videos/79240813 failed, reason: connect ETIMEDOUT 31.13.85.1:443',
>   type: 'system',
>   errno: 'ETIMEDOUT',
>   code: 'ETIMEDOUT' }
> (node:11168) UnhandledPromiseRejectionWarning: FetchError: request to https://api.twitch.tv/kraken/videos/79240813 failed, reason: connect ETIMEDOUT 31.13.85.1:443
>     at ClientRequest.<anonymous> (C:\Users\TF\AppData\Roaming\npm\node_modules\twitch-chatlog\node_modules\node-fetch\lib\index.js:1455:11)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at TLSSocket.socketErrorListener (_http_client.js:387:9)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> (node:11168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:11168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by freaktechnik** [comment]
I'm sorry, but this looks like a network issue on your side, or possibly an invalid client ID.
