### ISSUE TITLE
Syntax Error: Unexpected Token =

### ISSUE THREAD

**Issue by aspenrussellmedia** [freaktechnik/twitch-chatlog#15]
The error is found in the index file on line 63: 
function searchChat(start, length, vodID, c = false, progress = false, workerCount = 1, testServer) {...

I installed node version 4.6.0, NPM version 2.15.9
I then followed instructions and installed via 'npm install -g twitch-chatlog'

In the nodejs directory I ran 'twitch-chatlog v94562809' and the error popped. I went through all of the examples and they popped the same error as well.

I am new to node.js, so any help would be appreciated!

Best,

Aspen

**Comment by freaktechnik** [comment]
That's because this is not compatible with node 4. The engines value is set to >= 5 for a reason (https://github.com/freaktechnik/twitch-chatlog/blob/master/package.json#L10) and npm should warn you about that when installing.

**Comment by freaktechnik** [comment]
(I think it should actually be 6.* by now, probably forgot to update that)

**Comment by aspenrussellmedia** [comment]
Alright, updated to the latest version of node.js and now I receive this error:
Could not load VOD details: Bad Request

From this request: twitch-chatlog v79240813
and from this one: twitch-chatlog v94562809

Sorry for the confusion.

**Comment by freaktechnik** [comment]
that can occasionally happen, as outlined in the README.

**Comment by aspenrussellmedia** [comment]
Alright, everything appears to be working. Outside of the occasional bad request error.

Thanks for the help!

**Comment by ndarville** [comment]
@aspenrussellmedia You can also get an error if the VOD has no comments on it fwiw.
