### ISSUE TITLE
getaddrinfo ENOTFOUND rechat.twitch.tv rechat.twitch.tv:443

### ISSUE THREAD

**Issue by dinosaw** [freaktechnik/twitch-chatlog#56]
Hello again. Apologies for the new issue, but since you solved #54 it's now telling me what the actual error is. Not sure what I could be doing wrong, as like I said, it was working fine.

For this test I made sure I updated to the most recent version of twitch-chatlog and node. I also included the Video ID so you can verify that there is chat occurring within the first 60 seconds.

```
[root@dino ~]# node --version
v7.10.1
[root@dino ~]# twitch-chatlog --version
4.0.1
[root@dino ~]#
[root@dino ~]# twitch-chatlog -p -l 60 -C XXXXXXXXXXXXXXXXXXXX 180455106
{ FetchError: request to https://rechat.twitch.tv/rechat-messages?start=1507399497&video_id=v180455106 failed, reason: getaddrinfo ENOTFOUND rechat.twitch.tv rechat.twitch.tv:443
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v7.10.1/lib/node_modules/twitch-chatlog/node_modules/node-fetch/lib/index.js:1279:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'request to https://rechat.twitch.tv/rechat-messages?start=1507399497&video_id=v180455106 failed, reason: getaddrinfo ENOTFOUND rechat.twitch.tv rechat.twitch.tv:443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
(node:21807) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to https://rechat.twitch.tv/rechat-messages?start=1507399497&video_id=v180455106 failed, reason: getaddrinfo ENOTFOUND rechat.twitch.tv rechat.twitch.tv:443
(node:21807) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I see mention on the Twitch dev forums that `rechat.twitch.tv` isn't officially supported and could change without notice. With that in mind I attempted to dig/ping that domain from multiple machines but it doesn't resolve. Could that be the problem or not really?

Thanks!

**Comment by freaktechnik** [comment]
It is very possible that due to the new commenting system on VODs the rechat system was retired. I'll look into it.

**Comment by freaktechnik** [comment]
It seems indeed that chat logs were moved to VOD comments instead.

**Comment by freaktechnik** [comment]
I have pushed a fixed version to the master branch of this repo. I've published it on the pre tag on npm. To install it use, `npm i -g twitch-chatlog@pre`. Please report back if you find any issues there with a new issue. Thanks!

**Comment by dinosaw** [comment]
Tested and verified `@pre` working as intended. Thanks!
