### ISSUE TITLE
Heads up: API Client ID has expired

### ISSUE THREAD

**Issue by shiftypenguin** [freaktechnik/twitch-chatlog#62]
Just letting you know that the client ID that's baked in has now expired. Substituting a valid ID with `-C` works just fine, though. Maybe worth updating the README and removing the default ID. Maybe fail with a warning if no ID is given on the commandline?

**Comment by freaktechnik** [comment]
I do not see any issues with the built-in Client ID. Are you on the version that is updated to no longer use rechat.twitch.tv? And what do you see that makes would point to the client ID having expired?

**Comment by shiftypenguin** [comment]
Sorry, I must have been mistaken. I get the following error when I run `twitch-chatlog 183308708`:
```
{ RequestError: Could not load VOD details: Bad Request
    at fetch.then (/usr/local/lib/node_modules/twitch-chatlog/lib/index.js:55:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'RequestError',
  response: 
   Response {
     body: 
      PassThrough {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     size: 0,
     timeout: 0,
     url: 'https://api.twitch.tv/kraken/videos/183308708',
     status: 400,
     statusText: 'Bad Request',
     headers: Headers { [Symbol(map)]: [Object] },
     [Symbol(disturbed)]: false },
  message: 'Could not load VOD details: Bad Request' }
(node:28703) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Could not load VOD details: Bad Request
(node:28703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The same command succeeds when given a valid ID with `-C`. I'm running version 5.0.0-0 from npm.

**Comment by shiftypenguin** [comment]
I should also note that it's now failing without an ID on streams that I've previously gotten chat from.

**Comment by freaktechnik** [comment]
It's actually a typo in the binary. I'll release a fix as 5.0.0

**Comment by freaktechnik** [comment]
So https://github.com/freaktechnik/twitch-chatlog/releases/tag/v5.0.0 should fix that.

**Comment by shiftypenguin** [comment]
Cheers! Apologies for the incorrect diagnosis.

**Comment by freaktechnik** [comment]
No problem, it's hard to really know what's wrong, other than the Client ID being invalid.
